### PR TITLE
Propose guidelines change

### PR DESCRIPTION
**Pull request by zerebos**

### CODE REVIEW

**Comment by Huderon** [comment]
Maybe something more like 

> Themes should provide a cohesive design that notably alters the look and feel of Discord. The design should seamlessly integrate with any unthemed sections, ensuring a smooth and consistent experience across the entire interface

**Comment by zerebos** [comment]
@Huderon Updating the wording based on your suggestion

**Comment by Huderon** [comment]
Yeah, that looks good. If/when snippets are being considered it's only really this 

> - Try to leave as few unthemed sections as possible in order to improve the user experience.

That might need to change

**Comment by zerebos** [comment]
Agreed, I think snippets (as a full-blown addon) are a fair ways off for now... But snippets as a concept...

**Pull request merged**
